---
name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - bicep/**
  pull_request:
    branches:
      - main
    paths:
      - bicep/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  validate_prod:
    name: Validate Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Analyze Azure resources using PSRule for Azure
      - name: Analyze Azure template files
        uses: microsoft/ps-rule@v2.9.0
        with:
          modules: 'PSRule.Rules.Azure'

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
