---
name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - bicep/**
  pull_request:
    branches:
      - main
    paths:
      - bicep/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP_NAME: AvianTranslator
  LOCATION: westeurope

jobs:
  validate_prod:
    name: Validate Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: echo
        run: |
            echo ${{ github.workspace }}
            echo $GITHUB_WORKSPACE

      # Analyze Azure resources using PSRule for Azure
      - name: Analyze Azure template files
        uses: microsoft/ps-rule@v2.9.0
        with:
          modules: 'PSRule.Rules.Azure'

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate Azure Resource Group
        run: >
            az deployment sub validate
            --name reource-group-validate
            --resource-group ${{ env.RESOURCE_GROUP_NAME}}
            --template-file ${{ github.workspace }}/bicep/modules/resource-group.bicep
            --parameters ${{ github.workspace }}/bicep/parameters.resource-group.json

      - name: What-if Azure Resource Group
        run: >
              az deployment sub what-if
              --name resource-group-what-if
              --resource-group ${{ env.RESOURCE_GROUP_NAME}}
              --template-file ${{ github.workspace }}/bicep/modules/resource-group.bicep
              --parameters ${{ github.workspace }}/bicep/parameters.resource-group.json

      - name: Validate Azure SQL Server
        run: >
          az deployment group validate
          --name AzureSqlServer-validate
          --resource-group ${{ env.RESOURCE_GROUP_NAME}}
          --template-file ${{ github.workspace }}/bicep/modules/azure-sqlserver.bicep
          --parameters ${{ github.workspace }}/bicep/parameters.azure-sqlserver.json

      - name: What-if Azure SQL Server
        run: >
            az deployment group what-if
            --name AzureSqlServer-what-if
            --resource-group ${{ env.RESOURCE_GROUP_NAME}}
            --template-file ${{ github.workspace }}/bicep/modules/azure-sqlserver.bicep
            --parameters ${{ github.workspace }}/bicep/parameters.azure-sqlserver.json
